from app.mapper.servicenow_mapper import ServiceNowTaskMapper
from app.models import ExecutionTask, OperationType


def test_create_incident_mapping_contains_required_fields():
    task = ExecutionTask(
        execution_id="exec-1",
        task_id="task-1",
        investigation_id="inv-1",
        correlation_id="corr-1",
        tenant_id="tenant-1",
        operation=OperationType.CREATE_INCIDENT,
        payload={"threat_type": "account_takeover", "confidence": 88, "risk": "HIGH", "snapshot_version": 7},
        priority=90,
    )
    request = ServiceNowTaskMapper().map_to_request(task)
    assert request.method == "POST"
    assert request.endpoint == "/api/now/table/incident"
    assert request.payload["u_execution_id"] == "exec-1"
    assert "Generated by SentinelIQ" in request.payload["description"]


def test_lookup_user_mapping_uses_sys_user_table():
    task = ExecutionTask(
        execution_id="exec-2",
        task_id="task-2",
        investigation_id="inv-2",
        correlation_id="corr-2",
        tenant_id="tenant-1",
        operation=OperationType.LOOKUP_USER,
        payload={"user_name": "alice"},
        priority=50,
    )
    request = ServiceNowTaskMapper().map_to_request(task)
    assert request.method == "GET"
    assert request.endpoint == "/api/now/table/sys_user"
