TOPICS = {
    "UNIFIED_EVENTS": "events.unified.v1",
    "EVIDENCE_GRAPH_EVENTS": "evidence.graph.events.v1",
    "KNOWLEDGE_GRAPH_UPDATED": "knowledge.graph.updated.v1",
    "INVESTIGATIONS_UPDATED": "investigations.updated.v1",
    "AI_RESPONSES": "ai.responses.v1",
    "EXECUTION_REQUESTS": "execution.requests.v1",
    "EXECUTION_STATUS": "execution.status.v1",
    "AUDIT_EVENTS": "audit.events.v1",
    "NORMALIZED_EVENTS": "normalized-events.v1",
    "INVESTIGATION_CANDIDATES": "investigation.candidates.v1",
    "INVESTIGATION_COMPLETED": "investigation.completed.v1",
    "CASE_CREATED": "case.created.v1",
    "REPORT_GENERATED": "report.generated.v1",
    "EXECUTION_COMPLETED": "execution.completed.v1",
}
