from __future__ import annotations

from typing import Any, Dict

from app.models import ExecutionTask, IncidentPayload, OperationType, ServiceNowRequest


class ServiceNowTaskMapper:
    def map_to_request(self, task: ExecutionTask) -> ServiceNowRequest:
        if task.operation == OperationType.CREATE_INCIDENT:
            payload = self._incident_payload(task)
            return ServiceNowRequest(
                method="POST",
                endpoint="/api/now/table/incident",
                payload=payload,
                idempotency_key=task.execution_id,
            )
        if task.operation == OperationType.GET_INCIDENT:
            sys_id = str(task.payload.get("sys_id", ""))
            return ServiceNowRequest(
                method="GET",
                endpoint=f"/api/now/table/incident/{sys_id}",
                idempotency_key=task.execution_id,
            )
        if task.operation == OperationType.UPDATE_INCIDENT:
            sys_id = str(task.payload.get("sys_id", ""))
            update_payload = dict(task.payload.get("update", {}))
            return ServiceNowRequest(
                method="PATCH",
                endpoint=f"/api/now/table/incident/{sys_id}",
                payload=update_payload,
                idempotency_key=task.execution_id,
            )
        if task.operation == OperationType.LOOKUP_USER:
            user_query = str(task.payload.get("user_name") or task.payload.get("email") or "")
            return ServiceNowRequest(
                method="GET",
                endpoint="/api/now/table/sys_user",
                query={"sysparm_query": f"user_name={user_query}" if "@" not in user_query else f"email={user_query}", "sysparm_limit": 1},
                idempotency_key=task.execution_id,
            )
        if task.operation == OperationType.LOOKUP_CMDB_CI:
            name = str(task.payload.get("name", ""))
            return ServiceNowRequest(
                method="GET",
                endpoint="/api/now/table/cmdb_ci",
                query={"sysparm_query": f"name={name}", "sysparm_limit": 1},
                idempotency_key=task.execution_id,
            )
        if task.operation == OperationType.CREATE_CHANGE_REQUEST:
            payload = dict(task.payload.get("change", {}))
            return ServiceNowRequest(
                method="POST",
                endpoint="/api/now/table/change_request",
                payload=payload,
                idempotency_key=task.execution_id,
            )
        raise ValueError(f"unsupported operation: {task.operation.value}")

    def dry_run_preview(self, task: ExecutionTask) -> Dict[str, Any]:
        request = self.map_to_request(task)
        return {
            "execution_id": task.execution_id,
            "task_id": task.task_id,
            "operation": task.operation.value,
            "request": request.model_dump(mode="json"),
        }

    def _incident_payload(self, task: ExecutionTask) -> Dict[str, Any]:
        context = dict(task.payload)
        threat_type = str(context.get("threat_type", "unknown"))
        confidence = str(context.get("confidence", "unknown"))
        risk = str(context.get("risk", "unknown"))
        evidence_summary = str(context.get("evidence_summary", "not provided"))
        timeline_summary = str(context.get("timeline_summary", "not provided"))
        recommendations = str(context.get("recommendations", "not provided"))
        snapshot_version = str(context.get("snapshot_version", "unknown"))
        incident = IncidentPayload(
            short_description=str(context.get("short_description") or f"SentinelIQ Alert {task.investigation_id}"),
            description=(
                f"Threat Type: {threat_type}\n"
                f"Confidence: {confidence}\n"
                f"Risk: {risk}\n"
                f"Evidence Summary: {evidence_summary}\n"
                f"Timeline Summary: {timeline_summary}\n"
                f"Recommendations: {recommendations}\n"
                "Generated by SentinelIQ"
            ),
            priority=str(context.get("priority", "3")),
            impact=str(context.get("impact", "3")),
            urgency=str(context.get("urgency", "3")),
            category=str(context.get("category", "security")),
            work_notes=str(context.get("work_notes", "Created by SentinelIQ execution adapter")),
            correlation_id=task.correlation_id,
            investigation_id=task.investigation_id,
            execution_id=task.execution_id,
            snapshot_version=snapshot_version,
        )
        payload = incident.model_dump(mode="json")
        payload["u_correlation_id"] = task.correlation_id
        payload["u_investigation_id"] = task.investigation_id
        payload["u_execution_id"] = task.execution_id
        payload["u_snapshot_version"] = snapshot_version
        return payload
