from __future__ import annotations
from abc import ABC, abstractmethod
from typing import List, Optional
from shared.query import BaseQueryRepository
from .models import (
    AttackPattern, DetectionRule, FraudPattern, KnowledgeDetails, KnowledgeMetadata,
    KnowledgeRelationship, KnowledgeSearchRequest, KnowledgeSearchResponse,
    KnowledgeStatistics, KnowledgeValidation, MITRETactic, MITRETechnique,
    PatternVersion, Playbook, QuantumThreatPattern, KnowledgeRecommendation,
    SecurityControl, ThreatIndicator,
)


class KnowledgeRepository(BaseQueryRepository[KnowledgeSearchRequest, KnowledgeSearchResponse], ABC):
    @abstractmethod
    def find_item(self, item_id: str) -> Optional[KnowledgeDetails]: ...
    @abstractmethod
    def find_pattern(self, item_id: str) -> Optional[AttackPattern]: ...
    @abstractmethod
    def find_technique(self, item_id: str) -> Optional[MITRETechnique]: ...
    @abstractmethod
    def find_tactic(self, item_id: str) -> Optional[MITRETactic]: ...
    @abstractmethod
    def find_control(self, item_id: str) -> Optional[SecurityControl]: ...
    @abstractmethod
    def find_recommendation(self, item_id: str) -> Optional[KnowledgeRecommendation]: ...
    @abstractmethod
    def find_playbook(self, item_id: str) -> Optional[Playbook]: ...
    @abstractmethod
    def find_fraud_pattern(self, item_id: str) -> Optional[FraudPattern]: ...
    @abstractmethod
    def find_detection_rule(self, item_id: str) -> Optional[DetectionRule]: ...
    @abstractmethod
    def find_indicator(self, item_id: str) -> Optional[ThreatIndicator]: ...
    @abstractmethod
    def find_quantum_pattern(self, item_id: str) -> Optional[QuantumThreatPattern]: ...
    @abstractmethod
    def find_relationship(self, relationship_id: str) -> Optional[KnowledgeRelationship]: ...
    @abstractmethod
    def relationships(self, item_id: str) -> List[KnowledgeRelationship]: ...
    @abstractmethod
    def metadata(self) -> KnowledgeMetadata: ...
    @abstractmethod
    def statistics(self) -> KnowledgeStatistics: ...
    @abstractmethod
    def validate(self) -> KnowledgeValidation: ...
    @abstractmethod
    def versions(self, item_id: str) -> List[PatternVersion]: ...
    @abstractmethod
    def similar(self, item_id: str, limit: int = 10) -> List[KnowledgeDetails]: ...
